### PR TITLE
Fixes Playerinfo error

### PR DESCRIPTION
**Pull request by MarkSuckerberg**
Nothing special, just makes the bot send `No results found.` instead of returning an error when a player not in the database is searched for. Really just a copy/paste from findplayer, which already had those checks (also includes a few exception checks). Just thought I'd fix it since it was relatively easy to do. Tested.

image

image

### CODE REVIEW

**Comment by Crossedfall** [comment]
Op, got a new commit in the works that addresses this and adds an extra few sanity checks. Going to close this in favor of that, but thank you for sending a fix up!

**Comment by Crossedfall** [comment]
see https://github.com/Crossedfall/crossed-cogs/commit/00ac3620a16de2946b6ad648c2b89f19eb8da14a

**Comment by MarkSuckerberg** [comment]
Hey, as long as it’s fixed I’m happy

**Comment by Crossedfall** [comment]
Fixes are in: https://github.com/Crossedfall/crossed-cogs/commit/00ac3620a16de2946b6ad648c2b89f19eb8da14a and https://github.com/Crossedfall/crossed-cogs/commit/9306a02354a93eada79bd6712eed1d37dc92c672

**Pull request closed without merging**
